### ISSUE TITLE
[Insight] Public methods in controller classes should only be actions - in src/…/Controller/ClientController.php, line 27

### ISSUE THREAD

**Issue by Lucas-H2N** [salonsalsa/agence_de_voyage#24]
**[in src/RocketfireAgenceMainBundle/Controller/ClientController.php, line 27](https://github.com/salonsalsa/agence_de_voyage/blob/25902001bfe4046958fe0515102cca0051857fe7/src/RocketfireAgenceMainBundle/Controller/ClientController.php#L27)**

> Non-action public method found in controller class

```php
     * @param Request $request
     * @return type
     * @Method({"GET","POST"})
     * @Route("/client/home", name="client_home")
     */
    public function clientHome(Request $request){
         return $this->render(
                        'RocketfireAgenceMainBundle:Default:client.home.html.twig');
    }
    
    
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/cd2422f6-7d34-47b8-a2c6-09f45011c2d1/analyses/16)_

**Comment by Riwat** [comment]
fait
