### ISSUE TITLE
[Insight] PHP code should follow PSR-1 basic coding standard - in src/…/Repository/clientRepository.php, line 11

### ISSUE THREAD

**Issue by Lucas-H2N** [salonsalsa/agence_de_voyage#26]
**[in src/RocketfireAgenceMainBundle/Repository/clientRepository.php, line 11](https://github.com/salonsalsa/agence_de_voyage/blob/ca8b62fcd1f90a4ee52dc336154bf1ff30346bd6/src/RocketfireAgenceMainBundle/Repository/clientRepository.php#L11)**

> Class names should be declared in `StudlyCaps`. You should rename this class to comply with PSR-1.

```php
 * clientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class clientRepository extends \Doctrine\ORM\EntityRepository
{
}

```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/cd2422f6-7d34-47b8-a2c6-09f45011c2d1/analyses/17)_

**Comment by Riwat** [comment]
fait noob
