### ISSUE TITLE
[Insight] Code should not be duplicated - in src/…/Entity/ClientAssociation.php, line 13

### ISSUE THREAD

**Issue by Lucas-H2N** [salonsalsa/agence_de_voyage#33]
**[in src/RocketfireAgenceMainBundle/Entity/ClientAssociation.php, line 13](https://github.com/salonsalsa/agence_de_voyage/blob/47d34e8340f5cef895227e8e7c4538b46e4473cd/src/RocketfireAgenceMainBundle/Entity/ClientAssociation.php#L13)**

> The next 212 lines appear both in `src/RocketfireAgenceMainBundle/Entity/ClientAssociation.php:13` and `src/RocketfireAgenceMainBundle/Entity/ClientEntreprise.php:13`.

```php
/**
 * ClientAssociation
 *
 * @ORM\Entity(repositoryClass="RocketfireAgenceMainBundle\Repository\clientRepository")
 */
class ClientAssociation extends Client
{
    /**
     * @var int
     */
    protected $numFax;
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/cd2422f6-7d34-47b8-a2c6-09f45011c2d1/analyses/20)_

**Comment by Riwat** [comment]
fait bordel de merde !!!!
