### ISSUE TITLE
[Insight] Code should not be duplicated - in src/…/Entity/Client.php, line 95

### ISSUE THREAD

**Issue by Lucas-H2N** [salonsalsa/agence_de_voyage#34]
**[in src/RocketfireAgenceMainBundle/Entity/Client.php, line 95](https://github.com/salonsalsa/agence_de_voyage/blob/47d34e8340f5cef895227e8e7c4538b46e4473cd/src/RocketfireAgenceMainBundle/Entity/Client.php#L95)**

> The next 121 lines appear both in `src/RocketfireAgenceMainBundle/Entity/Client.php:95` and `src/RocketfireAgenceMainBundle/Entity/ClientParticulier.php:59`.

```php
     *
     * @param string $nom
     *
     * @return client
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/cd2422f6-7d34-47b8-a2c6-09f45011c2d1/analyses/20)_

**Comment by Riwat** [comment]
fait
