### ISSUE TITLE
[Insight] Unused use statement should be avoided - in src/…/Form/ClientEntrepriseType.php, line 6

### ISSUE THREAD

**Issue by Lucas-H2N** [salonsalsa/agence_de_voyage#39]
**[in src/RocketfireAgenceMainBundle/Form/ClientEntrepriseType.php, line 6](https://github.com/salonsalsa/agence_de_voyage/blob/47d34e8340f5cef895227e8e7c4538b46e4473cd/src/RocketfireAgenceMainBundle/Form/ClientEntrepriseType.php#L6)**

> The class `Symfony\Component\OptionsResolver\OptionsResolver` is declared but never used. You should remove the `use` statement.

```php
<?php

namespace RocketfireAgenceMainBundle\Form;

use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use RocketfireAgenceMainBundle\Form\ClientType;

class ClientEntrepriseType extends ClientType
{
    /**
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/cd2422f6-7d34-47b8-a2c6-09f45011c2d1/analyses/20)_

**Comment by Riwat** [comment]
fait
