### ISSUE TITLE
Création de la compagnie aérienne 

### ISSUE THREAD

**Issue by Lucas-H2N** [salonsalsa/agence_de_voyage#4]
Créations des entités/contrôleur/vue de CompagnieAerienneVol et Compagnie Aérienne.
Vous n'avez pas à faire le CSS.
Noubliez pas les normes.

**Comment by PAFrancioso** [comment]
On vient de faire le pull request - nos deux CRUD sont OK, il y a juste la navigation qui est différente entre les deux CRUD car aucune convention n'était fixée.
