### ISSUE TITLE
[Insight] Text files should end with a newline character - in src/…/Form/ClientType.php, line 38

### ISSUE THREAD

**Issue by Lucas-H2N** [salonsalsa/agence_de_voyage#41]
**[in src/RocketfireAgenceMainBundle/Form/ClientType.php, line 38](https://github.com/salonsalsa/agence_de_voyage/blob/47d34e8340f5cef895227e8e7c4538b46e4473cd/src/RocketfireAgenceMainBundle/Form/ClientType.php#L38)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```php
    {
        return 'rocketfireagencemainbundle_client';
    }


}
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/cd2422f6-7d34-47b8-a2c6-09f45011c2d1/analyses/20)_

**Comment by Riwat** [comment]
fait
