### ISSUE TITLE
[Insight] Commented code should not be committed - in src/…/CompagnieAerienneVolController.php, line 55

### ISSUE THREAD

**Issue by Lucas-H2N** [salonsalsa/agence_de_voyage#44]
**[in src/RocketfireAgenceMainBundle/Controller/CompagnieAerienneVolController.php, line 55](https://github.com/salonsalsa/agence_de_voyage/blob/e128f83d8350f86d4dc8887a017df6abc408594c/src/RocketfireAgenceMainBundle/Controller/CompagnieAerienneVolController.php#L55)**

> Commented out code reduces readability and lowers the code confidence for other developers. If it's common usage for debug, it should not be committed. Using a version control system, such code can be safely removed.

```php
            // store a message for the very next request
            $this->addFlash('notice', 'Félicitations, insertion réussie.');
            // redirection pour le fun
//            return $this->redirectToRoute('hello_world', [
//                        'name' => 'compagnieAerienneVol']);
//            return $this->redirectToRoute('default');
            return $this->redirectToRoute('CompagnieAerienneVol_list');
        }
        return $this->render('RocketfireAgenceMainBundle:CompagnieAerienneVol:create_compagnie_aerienne_vol.html.twig', array(
                        'form' => $form->createView()
        ));
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/cd2422f6-7d34-47b8-a2c6-09f45011c2d1/analyses/21)_

**Comment by PAFrancioso** [comment]
Done
