### ISSUE TITLE
[Insight] Commented code should not be committed - in src/…/CompagnieAerienneVolController.php, line 122

### ISSUE THREAD

**Issue by Lucas-H2N** [salonsalsa/agence_de_voyage#45]
**[in src/RocketfireAgenceMainBundle/Controller/CompagnieAerienneVolController.php, line 122](https://github.com/salonsalsa/agence_de_voyage/blob/e128f83d8350f86d4dc8887a017df6abc408594c/src/RocketfireAgenceMainBundle/Controller/CompagnieAerienneVolController.php#L122)**

> Commented out code reduces readability and lowers the code confidence for other developers. If it's common usage for debug, it should not be committed. Using a version control system, such code can be safely removed.

```php
        if (!$compagnieAerienneVol) {
            throw $this->createNotFoundException(
                    'No compagnieAerienneVol found for id ' . $compagnieAerienneVolId
            );
//            // redirection
//            return $this->redirectToRoute('CompagnieAerienneVol_list');
        }
        $em->remove($compagnieAerienneVol);
        $em->flush();
        // store a message for the very next request
        $this->addFlash('notice', 'Suppression réussie.');
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/cd2422f6-7d34-47b8-a2c6-09f45011c2d1/analyses/21)_

**Comment by PAFrancioso** [comment]
Done (Pull Request)
